# Open API 버전 (주로 3.0.0을 이용한다.)
openapi: 3.0.0

# API 문서에 대한 정보 (버전, 제목, 설명)
info:
  version: '1.0.0'
  title: '솝커툰 API'
  description: '솝커툰 API'
  
# API 서버에 대한 정보
servers:
  # - url: "http://13.209.206.99:3000/api"
  # - url: "http//15.164.83.64:3000/api"
  - url: "http://localhost:3000/api"
    description: 솝커툰 API # 제공하는 API에 대한 설명

tags:
  - name: 상품
    description: 상품 (메인 페이지)
  - name: 로그인 및 회원가입
    description: 로그인 및 회원가입 관련
  - name: 마이페이지
    description: 마이페이지 관련

  - name: 웹툰
    description: 웹툰 관련
  - name: 웹툰 에피소드
    description: 웹툰 에피소드 관련
  - name: 댓글
    description: 댓글관련
  - name: 기타 기능
    description: 기타 기능 관련

# 각 URI에 대한 정보를 기재
paths:
  /product/regular:
    $ref: './paths/product/regular.yaml'
  /product/package:
    $ref: './paths/product/package.yaml'
  /product/custom:
    $ref: './paths/product/custom.yaml'
  /product/detail:
    $ref: './paths/product/detail.yaml'

  /auth/signin:
    $ref: './paths/auth/signin.yaml'
  /auth/signup: 
    $ref: './paths/auth/signup.yaml'

  /mypage/main:
    $ref: './paths/mypage/main.yaml'
  /mypage/orderlist:
    $ref: './paths/mypage/orderlist.yaml'
  /mypage/orderlist/detail:
    $ref: './paths/mypage/detail.yaml'
  /mypage/regular-delivery/product:
    $ref: './paths/mypage/regular-delivery/product.yaml'
  
  /mypage/regular-delivery/change:
    $ref: './paths/mypage/regular-delivery/change.yaml'
  /mypage/regular-delivery/change/address:
    $ref: './paths/mypage/regular-delivery/change/address.yaml'
  /mypage/regular-delivery/change/count-minus:
    $ref: './paths/mypage/regular-delivery/change/count-minus.yaml'
  /mypage/regular-delivery/change/count-plus:
    $ref: './paths/mypage/regular-delivery/change/count-plus.yaml'
  /mypage/regular-delivery/change/memo:
    $ref: './paths/mypage/regular-delivery/change/memo.yaml'
  /mypage/regular-deliver/change/cycle:
    $ref: './paths/mypage/regular-delivery/change/cycle.yaml'
  /mypage/regular-deliver/change/delivery-day:
    $ref: './paths/mypage/regular-delivery/change/delivery-day.yaml'
  /mypage/regular-deliver/change/cancel:
    $ref: './paths/mypage/regular-delivery/change/cancel.yaml'
  

  /mypage/regular-delivery/subscribe:
    $ref: './paths/mypage/regular-delivery/subscribe.yaml'

