get:
  tags:
    - 상품
  summary: 패키지 상품 리스트 보여주기
  parameters:
    - in: query
      name: main_category_id
      required: true
      schema:
        type: integer
      description: 카테고리 종류의 id (9~16)
    - in: query
      name: flag
      required: true
      schema: 
        type: integer
      description: |
        1: 인기순 (앱잼 때 구현 X)

        2: 최신순 (앱잼 때 구현 X)

        3: 가격 낮은 순 (구현 O)

        4: 가격 높은 순 (구현 O)
  responses:
    '200':
      description: 상품 데이터 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              message:
                type: string
                example: 데이터 조회 성공
              data:
                type: object
                example: {
                  product_count: 42,
                  product: [{
                    "product_id": "ab_1027492",
                    "name": "플레이팅 완벽하게 끝내기",
                    "main_img": "https://alasdlfknasfnlkafnasmdf.alzsdkfnlasndf",
                    "price": 58000,
                    "saled_price": 48900,
                  },
                  {
                    "product_id": "ab_1027492",
                    "name": "플레이팅 완벽하게 끝내기",
                    "main_img": "https://alasdlfknasfnlkafnasmdf.alzsdkfnlasndf",
                    "price": 58000,
                    "saled_price": 48900,
                  },
                    ...
                  ]
                }
    '400':
      $ref: '../../components/responses.yaml#400-NULL_VALUE'
    '400 ':
      $ref: '../../components/responses.yaml#400-WRONG_PARAMS'
    '500 ':
      $ref: '../../components/responses.yaml#500-INTERNAL_SERVER_ERROR'