get:
  tags:
    - 상품
  summary: 패키지 상품 리스트 조회
  parameters:
    - in: query
      name: category
      required: true
      schema:
        type: string
      description: |
        카테고리 이름 
        
        (ex. 공간확보의달인, 가전제품, 우리집관리, 홈카페, 포근하게자기 )
        
        (주의. 띄어쓰기 하지 말 것)
        
    - in: query
      name: flag
      required: true
      schema: 
        type: integer
      description: |
        1: 최신순 (구현 O)

        2: 인기순 (앱잼 때 구현 X)

        3: 가격 낮은 순 (구현 O)

        4: 가격 높은 순 (구현 O)
  responses:
    '200':
      description: 상품 데이터 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              message:
                type: string
                example: 데이터 조회 성공
              data:
                type: object
                example: {
                  package_count: 42,
                  packages: [{
                    "package_id": "ab_1027492",
                    "name": "플레이팅 완벽하게 끝내기",
                    "main_img": "https://alasdlfknasfnlkafnasmdf.alzsdkfnlasndf",
                    "price": 58000,
                    "saled_price": 48900,
                  },
                  {
                    "package_id": "ab_1027492",
                    "name": "플레이팅 완벽하게 끝내기",
                    "main_img": "https://alasdlfknasfnlkafnasmdf.alzsdkfnlasndf",
                    "price": 58000,
                    "saled_price": 48900,
                  },
                    ...
                  ]
                }
    '400':
      $ref: '../../components/responses.yaml#400-NULL_VALUE'
    '500':
      $ref: '../../components/responses.yaml#500-INTERNAL_SERVER_ERROR'