get:
  tags:
    - 마이페이지
  summary: 마이페이지 정기배송 관리 - '상품 확인' 화면
  parameters:
    - in: header
      name: token
      required: true
      schema: 
        type: string
      description: 로그인 토큰
  responses:
    '200':
      description: 상품 데이터 조회 성공
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              message:
                type: string
                example: 데이터 조회 성공
              data:
                type: array
                example: [{
                  "main_img": "asdlkfnaldfkasdf.asdflnasdklnfasd",
                  "name": "스파클 2L",
                  "delivery_cycle": "1달",
                  "delivery_day": 3
                },
                {
                  "main_img": "asdlkfnaldfkasdf.asdflnasdklnfasd",
                  "name": "세탁세제",
                  "delivery_cycle": "2달",
                  "delivery_day": 3
                }]
    # '400':
    #   $ref: '../../../components/responses.yaml#400-NULL_VALUE'
    # '400 ':
    #   $ref: '../../../components/responses.yaml#400-WRONG_PARAMS'
    # '500 ':
    #   $ref: '../../../components/responses.yaml#500-INTERNAL_SERVER_ERROR'